apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: nginx-example
  name: nginx-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-example
  template:
    metadata:
      labels:
        name: nginx-example
    spec:
      containers:
      - image: 443370672158.dkr.ecr.us-east-1.amazonaws.com/lepsey_repository:latest
        name: nginx
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    #service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipassoc-034705eef81a60b46
spec:
  type: LoadBalancer
  selector:
    name: nginx-example
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

